CREATE MATERIALIZED VIEW {table_name}_mview AS
SELECT
    to_timestamp(concat(log_date, ' ', log_time), 'yyyy-MM-dd HH:mm:ss') AS `@timestamp`,
    c_ip AS `aws.cloudfront.c-ip`,
    NULL AS `aws.cloudfront.geo_location`,
    NULL AS `aws.cloudfront.geo_iso_code`,
    NULL AS `aws.cloudfront.geo_country`,
    NULL AS `aws.cloudfront.geo_city`,
    NULL AS `aws.cloudfront.ua_browser`,
    NULL AS `aws.cloudfront.ua_browser_version`,
    NULL AS `aws.cloudfront.ua_os`,
    NULL AS `aws.cloudfront.ua_os_version`,
    NULL AS `aws.cloudfront.ua_device`,
    NULL AS `aws.cloudfront.ua_category`,
    c_port AS `aws.cloudfront.c-port`,
    cs_cookie AS `aws.cloudfront.cs-cookie`,
    cs_host AS `aws.cloudfront.cs-host`,
    cs_referer AS `aws.cloudfront.cs-referer`,
    cs_user_agent AS `aws.cloudfront.cs-user-agent`,
    cs_bytes AS `aws.cloudfront.cs-bytes`,
    cs_method AS `aws.cloudfront.cs-method`,
    cs_protocol AS `aws.cloudfront.cs-protocol`,
    cs_protocol_version AS `aws.cloudfront.cs-protocol-version`,
    cs_uri_query AS `aws.cloudfront.cs-uri-query`,
    cs_uri_stem AS `aws.cloudfront.cs-uri-stem`,
    fle_encrypted_fields AS `aws.cloudfront.fle-encrypted-fields`,
    fle_status AS `aws.cloudfront.fle-status`,
    sc_bytes AS `aws.cloudfront.sc-bytes`,
    sc_content_len AS `aws.cloudfront.sc-content-len`,
    sc_content_type AS `aws.cloudfront.sc-content-type`,
    sc_range_end AS `aws.cloudfront.sc-range-end`,
    sc_range_start AS `aws.cloudfront.sc-range-start`,
    sc_status AS `aws.cloudfront.sc-status`,
    ssl_cipher AS `aws.cloudfront.ssl-cipher`,
    ssl_protocol AS `aws.cloudfront.ssl-protocol`,
    time_taken AS `aws.cloudfront.time-taken`,
    time_to_first_byte AS `aws.cloudfront.time-to-first-byte`,
    x_edge_detailed_result_type AS `aws.cloudfront.x-edge-detailed-result-type`,
    x_edge_location AS `aws.cloudfront.x-edge-location`,
    x_edge_request_id AS `aws.cloudfront.x-edge-request-id`,
    x_edge_result_type AS `aws.cloudfront.x-edge-result-type`,
    x_edge_response_result_type AS `aws.cloudfront.x-edge-response-result-type`,
    x_forwarded_for AS `aws.cloudfront.x-forwarded-for`,
    x_host_header AS `aws.cloudfront.x-host-header`
FROM
    {table_name};
