AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for Creating an IAM Role with Inline Policies

Parameters:
  AccountId:
    Type: String
    Description: 12 Digit AWS Account ID where the Security Lake data is stored.
  SecurityLakeBucketName:
    Type: String
    Description: Name of the S3 bucket which stores your Seucrity Lake data. It should look like this - aws-security-data-lake-ap-southeast-1-xxxxxxxxxxx
  SQSARN:
    Type: String
    Description: ARN of the SQS queue from your Security Lake subscriber. It should look like this - arn:aws:sqs:ap-southeast-1:xxxxxxxx:AmazonSecurityLake-xxxxx-xxxx-xxxx-xxx-bd11d35431d9-Main-Queue
  Region:
    Type: String
    Description: AWS region for the SQS queue
  DomainName:
    Type: String
    Description: Name of the OpenSearch domain. It should look like this - securitylake-os-0a36a962b287

Resources:
  OSIPipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: osis-pipelines.amazonaws.com
          Action: 'sts:AssumeRole'
      RoleName: 'OpenSearchIngestionRole'

      Policies:
      - PolicyName: Read-from-Security-Lake
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: ReadFromS3
            Effect: Allow
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${SecurityLakeBucketName}/*'
          - Sid: ReceiveAndDeleteSqsMessages
            Effect: Allow
            Action:
            - 'sqs:DeleteMessage'
            - 'sqs:ReceiveMessage'
            - 'sqs:changemessagevisibility'
            Resource: !Sub '${SQSARN}'
      - PolicyName: Write-to-OpenSearch
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: 'es:DescribeDomain'
            Resource: !Sub 'arn:aws:es:*:${AccountId}:domain/*'
          - Effect: Allow
            Action: 'es:ESHttp*'
            Resource: !Sub 'arn:aws:es:*:${AccountId}:domain/${DomainName}/*'

Outputs:
  IAMRoleArn:
    Description: ARN of the created OSIPipelineRole role
    Value: !GetAtt OSIPipelineRole.Arn

                    